---
- name: Manage GNS3 devices
  hosts: all
  connection: local
  
  tasks:
    - name: Global SNMP Settings
      ios_config:
        lines:
          - snmp-server community Test1 RO
          - snmp-server community Test2 RW
